version: '3'

services:
# back-end
  api:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: adamant-server
    volumes:
      - ./backend/conf:/app/conf
      - "adamant-schemas:/app/schemas"
    networks:
      - adamant
 # front-end 
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: adamant-client
    ports:
      - "3000:80"
    networks:
      - adamant

volumes:
  adamant-schemas:

networks:
  adamant:
    driver: bridge
    driver_opts:  # MTU needs to be lower or equal than the MTU of eth0
      com.docker.network.driver.mtu: 1450
